spring.application.name=Billing_software

# Render injects PORT automatically
server.port=${PORT:8080}

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d7sov4l7vvec73c7i4gg-a.oregon-postgres.render.com:5432/billing_1cgv?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:billing_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:x6IgQyt0uZ9Lw4o6WWmYRLGLRKAIBBtM}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.open-in-view=false